[project]
name = "FiniteMonkey"
version = "0.0.1"
description = "Intelligent vulnerability mining engine."
authors = [{ name = "Xue Yue" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"

dependencies = [
    "antlr4-python3-runtime==4.13.2",
    "certifi>=2024.8.30",
    "charset-normalizer>=3.4.0",
    "colorama>=0.4.6",
    "et-xmlfile>=1.1.0",
    "idna>=3.10",
    "joblib>=1.4.2",
    "lancedb>=0.24.0",
    "numpy>=1.24.4",
    "openai>=1.93.1",
    "openpyxl>=3.1.5",
    "pandas>=1.24.4",
    "psycopg2-binary>=2.9.9",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.0.1",
    "pytz>=2024.2",
    "requests>=2.32.3",
    "scikit-learn>=1.3.2",
    "scipy>=1.10.1",
    "simplejson>=3.19.3",
    "six>=1.16.0",
    "SQLAlchemy>=2.0.35",
    "threadpoolctl>=3.5.0",
    "tqdm>=4.66.5",
    "typing_extensions>=4.12.2",
    "tzdata>=2024.2",
    "urllib3>=2.2.3",
]

[project.optional-dependencies]

dev = ["mypy>=1.11.1", "ruff>=0.6.1"]

# [build-system]
# requires = ["setuptools>=73.0.0", "wheel"]
# build-backend = "setuptools.build_meta"

# [tool.setuptools]
# packages = ["assistant"]

# [tool.setuptools.package-dir]
# "assistant" = "src/assistant"

# [tool.setuptools.package-data]
# "*" = ["py.typed"]

[tool.ruff]
target-version = "py310"
line-length = 120
indent-width = 4
extend-exclude = ["docs", "test", "tests"]

[tool.ruff.lint]
select = ["F", "E"]
extend-select = ["W", "C90", "I", "N", "B", "A", "C4", "PERF", "RUF"]
ignore = ["I001"]
fixable = ["ALL"]
unfixable = []
preview = true
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
force-single-line = true
force-sort-within-sections = false
lines-after-imports = 2
known-first-party = []
known-local-folder = []
known-third-party = []
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.mccabe]
max-complexity = 24

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true

[tool.ruff.lint.pylint]
max-args = 5
max-branches = 12
max-locals = 15
max-statements = 50

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
preview = false
docstring-code-format = true

[tool.mypy]
# Platform configuration
python_version = "3.12"
# imports related
ignore_missing_imports = true
follow_imports = "silent"
# None and Optional handling
no_implicit_optional = false
strict_optional = false
# Configuring warnings
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
warn_return_any = false
# Untyped definitions and calls
check_untyped_defs = false
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_decorators = false
# Disallow dynamic typing
disallow_subclassing_any = false
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_generics = false
# Miscellaneous strictness flags
allow_untyped_globals = true
allow_redefinition = true
local_partial_types = false
implicit_reexport = true
strict_equality = true
# Configuring error messages
show_error_context = false
show_column_numbers = false
show_error_codes = true
exclude = ["docs", "test", "tests"]
